In [7]:
import torch
import numpy as np

# Tensor Tutorial

In [19]:
t = torch.randint(0,100,(10,10,5))

print(
    t.ndim, 
    t.dim(), 
    t.size()
    )


3 3 torch.Size([10, 10, 5])


torch.Size([10, 5])

### braodcasting rule for torch.matmul

torch.matmul(A,B) check list
```python
#if this return True, matmul possible
def check_list(A,B):
    if A.shape[-1] != B.shape[-2] :
        return False
    for a,b in zip(A.shape[:-2], B.shape[:-2]):
        if a == b or a==1 or b==1 : continue
        else : return False
    return True
```

In [ ]:
t1 = torch.randint(0,10, (5,5,2,3), dtype=torch.float)
t2 = torch.randint(10,20, (5,5,3,2), dtype=torch.float)


t1[0,0,0,0], t2[0,0,0,0], torch.matmul(t1,t2)


In [40]:
# torch.Tensor.mean(dim=i) function work averaging the dim axis.
for i in range(len(t1.shape)):
    print(t1.mean(dim=i).shape)

# torch.FloatTensor([[1,2,3],[4,5,6]]).mean(dim=0) equals [[(1+4)/2, (2+5)/2, (3+6)/2]]
print(torch.FloatTensor([[1,2,3],[4,5,6]]).mean(dim=0))

# torch.FloatTensor([[1,2,3],[4,5,6]]).mean(dim=1) equals [[(1+2+3)/3, (4+5+6)/3]]
torch.FloatTensor([[1,2,3],[4,5,6]]).mean(dim=1)

torch.Size([5, 2, 3])
torch.Size([5, 2, 3])
torch.Size([5, 5, 3])
torch.Size([5, 5, 2])
tensor([2.5000, 3.5000, 4.5000])


tensor([2., 5.])

### torch.max, torch.argmax  
인수 없이 쓸 경우(no param) : 모든 elements들 중, 최대 값 단 한개  
인수(dim)을 줄 경우 : dim으로 정해진 차원 외의 부분을 순회하며 dim 준 차원 값중 최대 값을 선택  

In [71]:
rand_tensor = torch.rand((5,5,2))
# print(rand_tensor)
idx = rand_tensor.argmax()
# 단 하나의 idx 값이므로, flatten 후 해당 idx값과 비교
print(rand_tensor.reshape(-1)[idx], rand_tensor.max())

tensor(0.9961) tensor(0.9961)


In [80]:
# dim 값 존재 시, max 함수는 argmax 와 max 값을 같이 출력
rand_tensor = torch.rand((3,3,4))
v, i = rand_tensor.max(dim=2) 
print(rand_tensor)  
for x in range(rand_tensor.shape[0]):
    for y in range(rand_tensor.shape[1]):
        print(v[x,y], rand_tensor[x,y,i[x,y]])

tensor([[[0.9086, 0.5848, 0.0370, 0.0715],
         [0.8166, 0.2186, 0.2770, 0.9911],
         [0.3400, 0.9930, 0.8842, 0.4852]],

        [[0.5974, 0.8312, 0.1563, 0.6105],
         [0.5388, 0.1573, 0.2952, 0.9887],
         [0.4068, 0.6409, 0.7916, 0.7368]],

        [[0.6253, 0.9810, 0.1864, 0.3195],
         [0.6170, 0.4023, 0.8528, 0.9583],
         [0.9065, 0.1554, 0.2389, 0.1906]]])
tensor(0.9086) tensor(0.9086)
tensor(0.9911) tensor(0.9911)
tensor(0.9930) tensor(0.9930)
tensor(0.8312) tensor(0.8312)
tensor(0.9887) tensor(0.9887)
tensor(0.7916) tensor(0.7916)
tensor(0.9810) tensor(0.9810)
tensor(0.9583) tensor(0.9583)
tensor(0.9065) tensor(0.9065)
